### ISSUE TITLE
Enable association with input events.

### ISSUE THREAD

**Issue by tdresser** [w3c/user-timing#15]
The browser has a lot of insight into input event timing that we don't currently expose to web developers. On the other hand, web developers have context on how input events are processed which the browser doesn't have.

If we provide an API along the lines of:

``` javascript
performance.markEventHandled(markName, associatedEvent);
```

we can associate the information the browser has on the input event with timing information the web developer provides.

We could use this information in a variety of ways, including:
- Displaying in devtools the time from when we send an event to the renderer until the app has responded to the event **including queueing time**.
- Integrating with `performance.measure` - we might be able to enable measuring the time between various stages in the input pipeline and a user mark.

**Comment by nolanlawson** [comment]
Now that [Chrome](https://developers.google.com/web/updates/2016/01/high-res-timestamps) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=77992) (and maybe soon Edge) are returning DOMHighResTimeStamp for Events rather than just timestamps, this seems like a good opportunity to figure out how to let users do `mark`/`measure` using input events.

E.g. it'd be nice to be able to define a custom mark A based on some input event, then create another mark B elsewhere, and then measure from A to B with a regular `performance.measure()`.

[As discussed on Twitter](https://twitter.com/Runspired/status/811085632176996352) with @runspired.

**Comment by tdresser** [comment]
I've done some more thinking on this [here](https://docs.google.com/document/d/15YAIJbv5x4hCVQx3cbUNRd9QSkyvS8bzbAMkcznNSjI/edit#heading=h.gtw9xl7781j1). I've spent a bit of time hacking on a polyfill (with completely terrible performance characteristics) - finishing it is my next step here.

That proposal is a bit monolithic, in the polyfill, I'm trying to split this functionality up into a few separate APIs.

**Comment by npm1** [comment]
I would think that this should be specified separately from UserTiming. Maybe it should go along the EventTiming API. In particular, I don't believe we plan to spec this for L3. Thoughts?

**Comment by yoavweiss** [comment]
Agree that this would probably fit under the EventTiming umbrella. @tdresser?

**Comment by tdresser** [comment]
Yup, agreed.
