### ISSUE TITLE
mark() and measure() return PerformanceEntries

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/user-timing#23]
https://github.com/w3c/resource-timing/issues/91

@igrigorik  @plehegar @nolanlawson 

Member 
nolanlawson commented 8 days ago 
Backstory:
https://twitter.com/Runspired/status/811018788820828160
https://github.com/nolanlawson/marky#api
#89 (comment)
Currently these APIs return void, which is kind of awkward if you actually want to grab the duration when you do a measure(). You could use PerformanceObserver, but then a library like marky would need its API to be asynchronous.
Is there any reason mark() and measure() can't directly return PerformanceEntries?
👍 1 
  

 
 nolanlawson referenced this issue 8 days ago 
 Open 
Increase limit of 150 for PerformanceEntrys? #89 

    
Member 
igrigorik commented 6 days ago 
Is there any reason mark() and measure() can't directly return PerformanceEntries?
I've wondered the same before.. It seems like a useful feature.
@plehegar do you recall any of the history of when this was first designed, and whether this was considered?

**Comment by JosephPecoraro** [comment]
If `mark` returns a PerformanceEntry then I think it would make a lot of sense for `measure` to also accept PerformanceEntries. Then you could have code like this:

```js
let startMark = performance.mark("start");
await task1();
performance.measure("measure-task1", startMark);
await task2();
performance.measure("measure-task2", startMark);
```

I would find this very natural. You have an explicit PerformanceEntry that you want to measure the time from, instead of a potentially non-unique string.

**Comment by philipwalton** [comment]
I'm supportive of both the proposal to have `performance.mark()` return a `PerformanceEntry` as well as having `performance.measure()` accept `PerformanceEntry` object (as I mentioned in https://github.com/w3c/user-timing/issues/22#issuecomment-330700372).

@igrigorik WDYT, can we do this for Level 2?

**Comment by igrigorik** [comment]
I like it. Also, I think it would also help cleanup the mess in https://github.com/w3c/user-timing/issues/22 -- correct?

**Comment by nolanlawson** [comment]
Based on discussion in the WG today, it sounds reasonable for `performance.measure()` to support:

- strings (user timing lookups, plus a frozen list of legacy nav 1 timing strings)
- `PerformanceEntry` objects
- numbers (`DOMHighResTimestamp`, e.g. a "custom user mark")

This works because `measure()` only needs access to the mark's `startTime`.

**Comment by igrigorik** [comment]
+1 to above. Couple additional notes from our conversation earlier today:

- L2 target: spec strings; get telemetry to see if we can deprecate long-term.
- L3 target: `PerformanceEntry`, numbers.

@nolanlawson @philipwalton would one (or both :)) be up for driving the spec work on either or both of the above?

**Comment by philipwalton** [comment]
Yeah, I can get started on the L2 work and look into adding telemetry on the Chrome side. Once we start on L3 stuff, I'll loop in @nolanlawson.

**Comment by nolanlawson** [comment]
Looking through the discussion, it seems allowing for arbitrary numbers would obviate the need for "Custom performance entries." Is that true, or is there still a need for this from e.g. the DevTools side of things?

From my POV it seems less awkward to just pass in a number to `measure()` instead of asking users to first make a custom "mark" entry and then reference it by name. (Or grab the object from the timeline and pass it in to `measure()`). It also seems like these measures could still appear in DevTools.

**Comment by philipwalton** [comment]
@nolanlawson agreed. @tdresser and I had a discussion recently and came to this exact same conclusion. We're going to try to write our thoughts down and share it with the group soon.

**Comment by jakub-g** [comment]
In addition to being able to refer to variables instead of strings, `performance.measure()` accepting `PerformanceEntry` objects will be helpful for example to refer to other browser measurements (First Paint, First Contentful Paint etc.) that do not extend the legacy `PerformanceTiming` interface:

```javascript
performance.mark('customEvent')
// ...
let fpEntry = performance.getEntriesByName('first-paint')
if (fpEntry[0]) {
  performance.measure('from FirstPaint to customEvent', fpEntry[0], 'customEvent')
}
```

This doesn't seem to be possible for now. It would be a very welcome change.

**Comment by npm1** [comment]
Closing this:

- mark() and measure() do return the corresponding entries in User Timing L3.

- mark() and measure() now support arbitrary timestamps, so in particular a timestamp from an arbitrary PerformanceEntry can be used.
