### ISSUE TITLE
Should performance.measure() work with resource timing entries?

### ISSUE THREAD

**Issue by philipwalton** [w3c/user-timing#27]
There are a lot of cases where you want to measure something and the start/end point is the max/min of two values. For example, to know when an image is actually visible on the page, you might need to take the max of (1) a `performance.mark()` immediately after the `<img>` element in the DOM, and (2) the `respondEnd` value of the images resource timing entry.

It's easy enough to get the max value in code, but if you wanted to then create a measure via `performance.measure()` from that value, AFAICT it's not possible.

I.e. it's not possible to do:

```js
performance.measure('hero image load', 'navigationStart', imageEntry.responseEnd);
```

Should `performance.measure()` be extended to accept a timestamp? The use case is if you're using a developer tool that adds visualization for measure entries.

**Comment by igrigorik** [comment]
Yep, not supported today.. and, yep, seems like a reasonable use case.

That said, I'm wondering if https://github.com/w3c/charter-webperf/issues/28 is a better (more generic) solution -- i.e. if we had custom metrics like what we outlined in that bug, I'm not sure we'd need UT at all.

**Comment by brusinow** [comment]
Allowing measures to take in resource timing values would be extremely useful. Using React as an example, these resource timings often complete after a given component's didMount lifecycle method has already fired - I'm not aware of another way to manually hook into individual resource completion in order to call performance.mark(). By adding resource timing support to performance.measure(), we could look at all resources loaded inside a specific component, find the slowest one, and calculate a more accurate component load time from that.
`performance.measure('myComponent', 'myComponentStart', slowestChildResource.responseEnd);`

**Comment by npm1** [comment]
UserTiming L3 allows arbitrary timestamps (in particular, you can pass in ResourceTiming timestamps), so closing this one.
