### ISSUE TITLE
measure API should return null

### ISSUE THREAD

**Issue by maxlgu** [w3c/user-timing#51]
For the old API:
PerformanceMeasure? measure(DOMString measureName, optional DOMString startMark, optional DOMString endMark);

In L2, we returned void for this API. PerformanceMeasure as a returned value was added later to distinguished between L2 and L3. As we no longer need to distinguish between L2 and L3 on it, should we change back to return void for this API?

**Comment by maxlgu** [comment]
@npm1

**Comment by npm1** [comment]
Returning the PerformanceMeasure was not meant to be a way to distinguish between L2 and L3, it's meant to make it more convenient to immediately obtain the object after performing a measure. Otherwise you'll need to do performance.getEntriesBy... Do you see any problem with measure() returning the PerformanceMeasure?

**Comment by maxlgu** [comment]
I agree it's more convenient. I don't see any problem of it. Thanks!
