### ISSUE TITLE
startOrOptions cannot be nullable

### ISSUE THREAD

**Issue by npm1** [w3c/user-timing#54]
As part of resolution to https://github.com/w3c/user-timing/issues/48 we decided to make startOrOptions nullable. But @bzbarsky pointed out that this is illegal per https://heycam.github.io/webidl/#idl-nullable-type, so we should remove the nullable.

The original issue for allowing it to be nullable was to distinguish {}, null, undefined. I claim that this is not necessary: they should all assume that none of the parameters were specified. This means that the end mark is determined by the other parameter (could end up being set to performance.now) and startTime is set to 0.

@maxlgu had previously looked at Chrome data which showed that only  0.01% of measures use undefined or null, so this should be OK.

**Comment by bzbarsky** [comment]
Undefined used to be treated as 0 already in the old API; that would not change with the proposal to treat empty dictionary as 0 start.

The behavior for null would change: the old version of the API treated it as a mark named "null" while the new API will treat it as an empty dictionary.

Note that the current spec says to throw for an empty dictionary as far as I can tell.  So that would need to change if we instead want to treat empty dictionary as 0.

This actually affects calls to `measure` with only one argument.  In the old spec, that would just use the given measure name.  In the new spec, it throws an exception, because the argument has a default value of empty dictionary (in particular, all the bits about "If startOrMeasureOptions is present" are confused: it is _always_ present.

**Comment by npm1** [comment]
> Undefined used to be treated as 0 already in the old API; that would not change with the proposal to treat empty dictionary as 0 start.

Yes, we intend to not change the behavior for undefined.

> 
> The behavior for null would change: the old version of the API treated it as a mark named "null" while the new API will treat it as an empty dictionary.

I'm ok with this changing since we were not supporting nullable in the first place.

> 
> Note that the current spec says to throw for an empty dictionary as far as I can tell. So that would need to change if we instead want to treat empty dictionary as 0.

Yes, I would change that while removing the nullable.

> 
> This actually affects calls to `measure` with only one argument. In the old spec, that would just use the given measure name. In the new spec, it throws an exception, because the argument has a default value of empty dictionary (in particular, all the bits about "If startOrMeasureOptions is present" are confused: it is _always_ present.

What I meant by present is that the optional parameter is defined. Maybe less confusing wording would be "If startOrMeasureOptions is not <code>undefined</code>"?

**Comment by bzbarsky** [comment]
> I'm ok with this changing since we were not supporting nullable in the first place.

I'm not sure what you mean, exactly...

> What I meant by present is that the optional parameter is defined.

My point is that by the time the spec algorithm runs the argument is always defined, present, whatever we want to call it.  (We should really add a term in the Web IDL spec for this; I'm not seeing one for arguments!)  That's because it has an implicit default value of "empty dictionary".   So if the JS passes `undefined` then on the spec algorithm side you will get an empty dictionary, just like if the JS passes `Object.create(null)` or `null` or (subject to some sanity assumptions) `{}`.

**Comment by bzbarsky** [comment]
And yes, I'm aware that's not what the Blink bindings do....

**Comment by npm1** [comment]
> I'm not sure what you mean, exactly...

What I mean is that before performance.measure("n", null, "end") would try to search the "null" mark for the startMark. In UserTiming L3 it will not do that (I think it will cast null to the empty dictionary), but that is fine because 1. null was never supported 2. data shows it's extremely rare usage.

> 
> > What I meant by present is that the optional parameter is defined.
> 
> My point is that by the time the spec algorithm runs the argument is always defined, present, whatever we want to call it. (We should really add a term in the Web IDL spec for this; I'm not seeing one for arguments!) That's because it has an implicit default value of "empty dictionary". So if the JS passes `undefined` then on the spec algorithm side you will get an empty dictionary, just like if the JS passes `Object.create(null)` or `null` or (subject to some sanity assumptions) `{}`.

Fair, so then the correct replacement is to say empty dictionary (and of course tweak the initial checks so that there is no error in that case).

**Comment by bzbarsky** [comment]
Ah, the relevant term in IDL is "missing" for operation arguments that are optional and `undefined` was passed.  The fact that I couldn't find it easily is not great; I filed https://github.com/heycam/webidl/issues/707 on that.

> 2. data shows it's extremely rare usage

This is the important point.  ;)

> so then the correct replacement is to say empty dictionary (and of course tweak the initial checks so that there is no error in that case).

Sounds great, thank you!

**Comment by annevk** [comment]
You can use https://infra.spec.whatwg.org/#map-is-empty for empty dictionaries as dictionaries are maps.
